name: authexample
env_file:
  - .lando.env
  - .lando.local.env
services:
  next:
    type: node:20
    port: 3000
    ssl: true
    sslExpose: true
    scanner:
      okCodes:
        - 404
        - 502
        - ECONNRESET
    build_as_root:
      - apt-get update -y && apt-get install -y --no-install-recommends apt-utils
      - apt-get update -y && apt-get install -y apt-transport-https build-essential unzip
    build:
      - mkdir -p /var/www/.npm-global/lib
      - cd /app/frontend && npm install
  pocketbase:
    type: go
    port: 8090
    scanner:
      okCodes:
        - 400
        - 401
        - 403
        - 404
        - 500
        - 502
        - 503
        - 504
        - ECONNRESET
    build_as_root:
      - apt-get update -y && apt-get install -y --no-install-recommends apt-utils unzip
      - wget https://github.com/pocketbase/pocketbase/releases/download/v0.22.21/pocketbase_0.22.21_linux_amd64.zip
      - rm -rf pocketbase/pb_data pocketbase/pocketbase pocketbase/CHANGELOG.md pocketbase/LICENSE.md
      - unzip pocketbase_0.22.21_linux_amd64.zip -d pocketbase
      - rm pocketbase_0.22.21_linux_amd64.zip
      - cd /app/pocketbase && ./pocketbase migrate up
      - cd /app/pocketbase && ./pocketbase admin create admin@example.com In5ecureP4S123
  api:
    type: go
    port: 8080
    ssl: true
    sslExpose: true
    scanner:
      okCodes:
        - 400
        - 401
        - 403
        - 404
        - 500
        - 502
        - 503
        - 504
        - ECONNRESET
    build_as_root:
      - apt-get update -y && apt-get install -y --no-install-recommends apt-utils unzip
      - cd /app/server && ./update-go.sh
      #- cd server && openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
events:
  post-start:
    - pocketbase: cd /app/pocketbase && ./pocketbase serve --http=0.0.0.0:8090 &
proxy:
  next:
    - authexample.lndo.site:3000
  pocketbase:
    - db.authexample.lndo.site:8090
  api:
    - api.authexample.lndo.site:8080
tooling:
  pb:
    service: pocketbase
    cmd: ./pocketbase
    dir: /app/pocketbase
  npm:
    service: next
    cmd: npm
    dir: /app/frontend
  npx:
    service: next
    cmd: npx
    dir: /app/frontend
  next:
    service: next
    cmd: npm run build && npm run start
    dir: /app/frontend
  api:
    service: api
    cmd: go run main.go serve
    dir: /app/server
